services:
  - type: web
    name: ml-backend
    env: python
    plan: free
    rootDir: .
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
